config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :entries
  end

  root :to => 'lists#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :list
  belongs_to :users
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :users, optional: true
  has_many :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    list = List.find(params[:list_id])
    @entries = list.entries
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    list = List.find(params[:list_id])
    @entry = list.entries.find_by_id(params[:id])
  end

  # GET /entries/new
  def new
    list = List.find(params[:list_id])
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
    list = List.find(params[:list_id])
    @entry = list.entries.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = list.entries.build(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @list, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @list, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to list_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:name, :completed)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all.order("created_at DESC")
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_user.lists.build(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: @entry, url: [@list, @entry]) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :entry_name %>
  </div>

  <div class="field">
    <%= form.check_box :completed, id: :entry_completed %>
    <%= form.label :completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/_list-entries.html.erb
<div class="list_entry">
  <p>List entries go here</p>
</div>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', list_entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.name %></td>
        <td><%= entry.completed %></td>
        <td><%= link_to 'Show', list_entry %></td>
        <td><%= link_to 'Edit', edit_list_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', list_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_list_entry_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', list_entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @entry.name %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @entry.completed %>
</p>

<%= link_to 'Edit', edit_list_entry_path(@entry) %> |
<%= link_to 'Back', list_entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listlist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :list_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>
    <% current_user.lists.each do |list| %>
    <div class="list_wrapper col-md-3">
      <div class="list_header">
        <h4><%= link_to list.name, list %></h4>
      </div>
      <div class="list_body">
        <%= render partial: 'entries/list-entries' %>
        <%= link_to 'Edit', edit_list_path(list) %></td>
        <%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    <% end %>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<div class="col-md-4">
  <p id="notice"><%= notice %></p>

  <div class="list_header">
    <h4><%= @list.name %></h4>
  </div>

  <div class="list_body">

  <%= render partial: 'entries/list-entries' %>

    <div class="actions">
      <%= link_to 'Edit', edit_list_path(@list) %> |
      <%= link_to 'Back', lists_path %>
    </div>
  </div>

</div>